### ISSUE TITLE
Valid CSS Rejected (with fix)

### ISSUE THREAD

**Issue by kittsville** [cytoscape/cytoscape.js#1658]
Hi,

Cytoscape rejects CSS blocks unless every statement ends with a semicolon:
![cytoscape error screenshot](https://cloud.githubusercontent.com/assets/6013087/21444817/b8db7078-c8a9-11e6-97c5-068fdef84524.png)
This means the following valid CSS snippets would cause Cytoscape to throw an exception:
```css
/* Valid CSS, causes Cytoscape error */
node {
    background-color: #000
}
```
```css
/* Also valid, causes Cytoscape error */
node {
    background-color: #000;
    label: data(name)
}
```
CSS2 and CSS3 specifications use semicolons as separators, meaning that the last statement of a block does not need a semicolon. Many CSS minifiers don't use semicolons in these situations to save space.

This bug is caused by the regex in [string-sheet.js](../blob/06e11b9c6792622d4d96be3da8b3001423465bff/src/style/string-sheet.js#L73), which requires a semicolon after every property.

I think you can fix this by replacing the 2nd capture block with an "anything but semicolon" greedy capture and making the semicolon optional:
`/^\s*(.+?)\s*:\s*([^;]+)\s*;?/`

I haven't submitted a pull with the change because I don't have node on this machine so it might cause tests to fail. Otherwise should just be a 5 second fix.
