### ISSUE TITLE
`triangle-backcurve` arrow can be be misaligned for thick edges

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#2067]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.2.8
- Browser/Node.js & version : Chrome v64, should affect all

**Current (buggy) behaviour**

The edge arrow is misaligned:

![screen shot 2018-02-15 at 12 25 56 pm](https://user-images.githubusercontent.com/989043/36271030-6928aca2-124b-11e8-9195-1ad1a0f5acb1.png)

**Desired behaviour**

Leave no extra space between the line and arrow.

**Minimum steps to reproduce**

Stylesheet:

```css
edge {
  width: 10px;
  target-arrow-shape: triangle-backcurve;
}
```
