### ISSUE TITLE
Multiple data()/mapData() in string stylesheet property value

### ISSUE THREAD

**Issue by shaedrich** [cytoscape/cytoscape.js#2704]
**Issue type**
Feature request

**Description of new feature**
When having a string stylesheet, something like this works fine:
```css
node {
    label: data(id);
}
```

but not this:
```css
node {
    label: data(type) ' ' data(id);
}
```

whereas something similar in native css works:
```css
span:before {
    content: attr(title) ': ' attr(href);
}
```

Is there a reason, you limited it to one call to either `data()` or `mapData()` or would you implement it?
