### ISSUE TITLE
Feature Request: CSS Variables

### ISSUE THREAD

**Issue by lukethacoder** [cytoscape/cytoscape.js#2733]
**Issue type**
Feature request

**Description of new feature**

Allow the use of css variables when styling.

Ideally we would drop in css variable similarly to how one would normally handle variables in css.

```css
style: [
  {
    selector: 'node',
    style: {
      height: 32,
      width: 32,
      color: 'var(--theme-brand)',
      'background-color': 'var(--theme-background)'
    },
  }
]
```

Not 100% across how the styling works behind the scenes with cytoscapejs, but I understand it is not just standard css. This feature may not even be possible due to how cytoscapejs is rendered in the canvas.

**Motivation for new feature**

Would allow for better theming and on the fly customisation, and integrate well with already established css variable theming within projects that are using it.
