### ISSUE TITLE
Add edge error

### ISSUE THREAD

**Issue by idoo** [cytoscape/cytoscape.js#991]
I try add edge same way
```
              cy.add
                group: "edges"
                data:
                  id: 'e' + Math.floor(Date.now())
                  source: sourceNode
                  target: targetNode
```
but get error

```
An element must be of type `nodes` or `edges`; you specified `function (){
      var ele = this[0];

      if( ele ){
        return ele._private.group;
      }
    }```
